

build:
	gcc -o BuildPilot.out BuildPilot.c

run: build
	./BuildPilot.out



h:
	@echo "Available commands:"
	@echo "  build - Compile the BuildPilot.c file"
	@echo "  run   - Compile and run the BuildPilot.out executable"
	@echo "  h     - Display this help message"